// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignTask(ctx context.Context, arg AssignTaskParams) error
	CancelJob(ctx context.Context, id pgtype.UUID) error
	CompleteTask(ctx context.Context, arg CompleteTaskParams) error
	CountJobs(ctx context.Context) (int64, error)
	CountJobsByStatus(ctx context.Context, status JobStatus) (int64, error)
	CountPendingTasksForJob(ctx context.Context, jobID pgtype.UUID) (int64, error)
	CountTasksByJobAndStatus(ctx context.Context, arg CountTasksByJobAndStatusParams) (int64, error)
	// ============================================
	// AUDIT LOG
	// ============================================
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateEncodingProfile(ctx context.Context, arg CreateEncodingProfileParams) (EncodingProfile, error)
	// ============================================
	// GLOBAL ERROR TRACKING
	// ============================================
	CreateErrorEvent(ctx context.Context, arg CreateErrorEventParams) (ErrorEvent, error)
	// ============================================
	// JOBS
	// ============================================
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	// ============================================
	// JOB LOGS
	// ============================================
	CreateJobLog(ctx context.Context, arg CreateJobLogParams) error
	// ============================================
	// NOTIFICATIONS
	// ============================================
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ============================================
	// RESTREAM JOBS
	// ============================================
	CreateRestreamJob(ctx context.Context, arg CreateRestreamJobParams) (RestreamJob, error)
	// ============================================
	// STREAMS
	// ============================================
	CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error)
	// ============================================
	// TASKS
	// ============================================
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// ============================================
	// WEBHOOKS
	// ============================================
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	DeactivateWebhook(ctx context.Context, id pgtype.UUID) error
	DeleteEncodingProfile(ctx context.Context, id string) error
	DeleteJob(ctx context.Context, id pgtype.UUID) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteOldAuditLogs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	DeleteOldErrorEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// ============================================
	// CLEANUP QUERIES
	// ============================================
	DeleteOldJobsByStatus(ctx context.Context, arg DeleteOldJobsByStatusParams) (int64, error)
	DeleteOldNotifications(ctx context.Context, userID pgtype.UUID) error
	DeleteOldWorkers(ctx context.Context, lastSeen pgtype.Timestamptz) (int64, error)
	DeleteOrphanedTasks(ctx context.Context) (int64, error)
	DeletePluginConfig(ctx context.Context, id string) error
	DeleteRestreamJob(ctx context.Context, id pgtype.UUID) error
	DeleteStream(ctx context.Context, id pgtype.UUID) error
	DeleteWebhook(ctx context.Context, id pgtype.UUID) error
	DeleteWorker(ctx context.Context, id string) error
	DisablePlugin(ctx context.Context, id string) error
	EnablePlugin(ctx context.Context, id string) error
	FailTask(ctx context.Context, arg FailTaskParams) error
	GetCompletedTaskOutputs(ctx context.Context, jobID pgtype.UUID) ([]GetCompletedTaskOutputsRow, error)
	// ============================================
	// ENCODING PROFILES
	// ============================================
	GetEncodingProfile(ctx context.Context, id string) (EncodingProfile, error)
	GetJob(ctx context.Context, id pgtype.UUID) (Job, error)
	GetPendingTasks(ctx context.Context, limit int32) ([]Task, error)
	GetPluginConfig(ctx context.Context, id string) (PluginConfig, error)
	GetRestreamJob(ctx context.Context, id pgtype.UUID) (RestreamJob, error)
	GetStream(ctx context.Context, id pgtype.UUID) (Stream, error)
	GetStreamByKey(ctx context.Context, streamKey string) (Stream, error)
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	GetUnreadNotificationCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetWebhook(ctx context.Context, id pgtype.UUID) (Webhook, error)
	GetWorker(ctx context.Context, id string) (Worker, error)
	IncrementTaskAttempt(ctx context.Context, id pgtype.UUID) error
	IncrementWebhookFailure(ctx context.Context, id pgtype.UUID) error
	ListActiveWebhooksForEvent(ctx context.Context, event string) ([]Webhook, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListEncodingProfiles(ctx context.Context) ([]EncodingProfile, error)
	ListErrorEvents(ctx context.Context, arg ListErrorEventsParams) ([]ErrorEvent, error)
	ListErrorEventsBySource(ctx context.Context, arg ListErrorEventsBySourceParams) ([]ErrorEvent, error)
	ListHealthyWorkers(ctx context.Context) ([]Worker, error)
	ListJobLogs(ctx context.Context, jobID pgtype.UUID) ([]JobLog, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error)
	ListJobsByUser(ctx context.Context, arg ListJobsByUserParams) ([]Job, error)
	ListLiveStreams(ctx context.Context) ([]Stream, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPluginConfigs(ctx context.Context) ([]PluginConfig, error)
	ListPluginConfigsByType(ctx context.Context, pluginType string) ([]PluginConfig, error)
	ListRestreamJobs(ctx context.Context, arg ListRestreamJobsParams) ([]RestreamJob, error)
	ListRestreamJobsByUser(ctx context.Context, arg ListRestreamJobsByUserParams) ([]RestreamJob, error)
	ListStreams(ctx context.Context, arg ListStreamsParams) ([]Stream, error)
	ListStreamsByUser(ctx context.Context, arg ListStreamsByUserParams) ([]Stream, error)
	ListTasksByJob(ctx context.Context, jobID pgtype.UUID) ([]Task, error)
	ListWebhooks(ctx context.Context) ([]Webhook, error)
	ListWebhooksByUser(ctx context.Context, userID pgtype.UUID) ([]Webhook, error)
	ListWorkers(ctx context.Context) ([]Worker, error)
	MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MarkWorkersUnhealthy(ctx context.Context) ([]Worker, error)
	// ============================================
	// PLUGIN CONFIGS
	// ============================================
	RegisterPluginConfig(ctx context.Context, arg RegisterPluginConfigParams) (PluginConfig, error)
	// ============================================
	// WORKERS
	// ============================================
	RegisterWorker(ctx context.Context, arg RegisterWorkerParams) error
	ResolveErrorEvent(ctx context.Context, id pgtype.UUID) error
	SetStreamArchiveJob(ctx context.Context, arg SetStreamArchiveJobParams) error
	UpdateEncodingProfile(ctx context.Context, arg UpdateEncodingProfileParams) error
	UpdateJobCompleted(ctx context.Context, id pgtype.UUID) error
	UpdateJobFailed(ctx context.Context, arg UpdateJobFailedParams) error
	UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error
	UpdateJobStarted(ctx context.Context, arg UpdateJobStartedParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdatePluginConfig(ctx context.Context, arg UpdatePluginConfigParams) error
	UpdateRestreamJobStatus(ctx context.Context, arg UpdateRestreamJobStatusParams) error
	UpdateStreamLive(ctx context.Context, arg UpdateStreamLiveParams) error
	UpdateStreamMetadata(ctx context.Context, arg UpdateStreamMetadataParams) error
	UpdateStreamRestreamDestinations(ctx context.Context, arg UpdateStreamRestreamDestinationsParams) error
	UpdateStreamStats(ctx context.Context, arg UpdateStreamStatsParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpdateWebhookTriggered(ctx context.Context, id pgtype.UUID) error
	UpdateWorkerHeartbeat(ctx context.Context, id string) error
	UpdateWorkerStatus(ctx context.Context, arg UpdateWorkerStatusParams) error
}

var _ Querier = (*Queries)(nil)
