// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/encoder.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capabilities struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	VideoCodecs          []string               `protobuf:"bytes,1,rep,name=video_codecs,json=videoCodecs,proto3" json:"video_codecs,omitempty"`
	AudioCodecs          []string               `protobuf:"bytes,2,rep,name=audio_codecs,json=audioCodecs,proto3" json:"audio_codecs,omitempty"`
	Containers           []string               `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	HardwareAcceleration bool                   `protobuf:"varint,4,opt,name=hardware_acceleration,json=hardwareAcceleration,proto3" json:"hardware_acceleration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_proto_encoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{0}
}

func (x *Capabilities) GetVideoCodecs() []string {
	if x != nil {
		return x.VideoCodecs
	}
	return nil
}

func (x *Capabilities) GetAudioCodecs() []string {
	if x != nil {
		return x.AudioCodecs
	}
	return nil
}

func (x *Capabilities) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Capabilities) GetHardwareAcceleration() bool {
	if x != nil {
		return x.HardwareAcceleration
	}
	return false
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_proto_encoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      float64                `protobuf:"fixed64,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Bitrate       int64                  `protobuf:"varint,5,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Streams       []*StreamInfo          `protobuf:"bytes,6,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_proto_encoder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeResult) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ProbeResult) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ProbeResult) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProbeResult) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ProbeResult) GetBitrate() int64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *ProbeResult) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodecType     string                 `protobuf:"bytes,1,opt,name=codec_type,json=codecType,proto3" json:"codec_type,omitempty"` // video, audio, subtitle
	CodecName     string                 `protobuf:"bytes,2,opt,name=codec_name,json=codecName,proto3" json:"codec_name,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_proto_encoder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{3}
}

func (x *StreamInfo) GetCodecType() string {
	if x != nil {
		return x.CodecType
	}
	return ""
}

func (x *StreamInfo) GetCodecName() string {
	if x != nil {
		return x.CodecName
	}
	return ""
}

func (x *StreamInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type TranscodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUrl     string                 `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	OutputUrl     string                 `protobuf:"bytes,2,opt,name=output_url,json=outputUrl,proto3" json:"output_url,omitempty"`
	Profile       *TranscodeProfile      `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeRequest) Reset() {
	*x = TranscodeRequest{}
	mi := &file_proto_encoder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeRequest) ProtoMessage() {}

func (x *TranscodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeRequest.ProtoReflect.Descriptor instead.
func (*TranscodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{4}
}

func (x *TranscodeRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *TranscodeRequest) GetOutputUrl() string {
	if x != nil {
		return x.OutputUrl
	}
	return ""
}

func (x *TranscodeRequest) GetProfile() *TranscodeProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type TranscodeProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoCodec    string                 `protobuf:"bytes,1,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,2,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Bitrate       int64                  `protobuf:"varint,5,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Container     string                 `protobuf:"bytes,6,opt,name=container,proto3" json:"container,omitempty"`
	Preset        string                 `protobuf:"bytes,7,opt,name=preset,proto3" json:"preset,omitempty"` // ultrafast, slow, etc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeProfile) Reset() {
	*x = TranscodeProfile{}
	mi := &file_proto_encoder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeProfile) ProtoMessage() {}

func (x *TranscodeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeProfile.ProtoReflect.Descriptor instead.
func (*TranscodeProfile) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{5}
}

func (x *TranscodeProfile) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *TranscodeProfile) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *TranscodeProfile) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TranscodeProfile) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TranscodeProfile) GetBitrate() int64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *TranscodeProfile) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *TranscodeProfile) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

type TranscodeProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       float32                `protobuf:"fixed32,1,opt,name=percent,proto3" json:"percent,omitempty"` // 0-100
	Speed         float64                `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`
	Frame         int64                  `protobuf:"varint,3,opt,name=frame,proto3" json:"frame,omitempty"`
	Eta           string                 `protobuf:"bytes,4,opt,name=eta,proto3" json:"eta,omitempty"`
	Completed     bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeProgress) Reset() {
	*x = TranscodeProgress{}
	mi := &file_proto_encoder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeProgress) ProtoMessage() {}

func (x *TranscodeProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeProgress.ProtoReflect.Descriptor instead.
func (*TranscodeProgress) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{6}
}

func (x *TranscodeProgress) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *TranscodeProgress) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TranscodeProgress) GetFrame() int64 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *TranscodeProgress) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *TranscodeProgress) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TranscodeProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_encoder_proto protoreflect.FileDescriptor

const file_proto_encoder_proto_rawDesc = "" +
	"\n" +
	"\x13proto/encoder.proto\x12\x02v1\x1a\x12proto/shared.proto\"\xa9\x01\n" +
	"\fCapabilities\x12!\n" +
	"\fvideo_codecs\x18\x01 \x03(\tR\vvideoCodecs\x12!\n" +
	"\faudio_codecs\x18\x02 \x03(\tR\vaudioCodecs\x12\x1e\n" +
	"\n" +
	"containers\x18\x03 \x03(\tR\n" +
	"containers\x123\n" +
	"\x15hardware_acceleration\x18\x04 \x01(\bR\x14hardwareAcceleration\" \n" +
	"\fProbeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xb3\x01\n" +
	"\vProbeResult\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x01R\bduration\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x18\n" +
	"\abitrate\x18\x05 \x01(\x03R\abitrate\x12(\n" +
	"\astreams\x18\x06 \x03(\v2\x0e.v1.StreamInfoR\astreams\"`\n" +
	"\n" +
	"StreamInfo\x12\x1d\n" +
	"\n" +
	"codec_type\x18\x01 \x01(\tR\tcodecType\x12\x1d\n" +
	"\n" +
	"codec_name\x18\x02 \x01(\tR\tcodecName\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"\x80\x01\n" +
	"\x10TranscodeRequest\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl\x12\x1d\n" +
	"\n" +
	"output_url\x18\x02 \x01(\tR\toutputUrl\x12.\n" +
	"\aprofile\x18\x03 \x01(\v2\x14.v1.TranscodeProfileR\aprofile\"\xd2\x01\n" +
	"\x10TranscodeProfile\x12\x1f\n" +
	"\vvideo_codec\x18\x01 \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\x02 \x01(\tR\n" +
	"audioCodec\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x18\n" +
	"\abitrate\x18\x05 \x01(\x03R\abitrate\x12\x1c\n" +
	"\tcontainer\x18\x06 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06preset\x18\a \x01(\tR\x06preset\"\x9f\x01\n" +
	"\x11TranscodeProgress\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x02R\apercent\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x01R\x05speed\x12\x14\n" +
	"\x05frame\x18\x03 \x01(\x03R\x05frame\x12\x10\n" +
	"\x03eta\x18\x04 \x01(\tR\x03eta\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\xa8\x01\n" +
	"\x0eEncoderService\x12.\n" +
	"\x0fGetCapabilities\x12\t.v1.Empty\x1a\x10.v1.Capabilities\x12*\n" +
	"\x05Probe\x12\x10.v1.ProbeRequest\x1a\x0f.v1.ProbeResult\x12:\n" +
	"\tTranscode\x12\x14.v1.TranscodeRequest\x1a\x15.v1.TranscodeProgress0\x01B,Z*github.com/rennerdo30/webencode/pkg/api/v1b\x06proto3"

var (
	file_proto_encoder_proto_rawDescOnce sync.Once
	file_proto_encoder_proto_rawDescData []byte
)

func file_proto_encoder_proto_rawDescGZIP() []byte {
	file_proto_encoder_proto_rawDescOnce.Do(func() {
		file_proto_encoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_encoder_proto_rawDesc), len(file_proto_encoder_proto_rawDesc)))
	})
	return file_proto_encoder_proto_rawDescData
}

var file_proto_encoder_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_encoder_proto_goTypes = []any{
	(*Capabilities)(nil),      // 0: v1.Capabilities
	(*ProbeRequest)(nil),      // 1: v1.ProbeRequest
	(*ProbeResult)(nil),       // 2: v1.ProbeResult
	(*StreamInfo)(nil),        // 3: v1.StreamInfo
	(*TranscodeRequest)(nil),  // 4: v1.TranscodeRequest
	(*TranscodeProfile)(nil),  // 5: v1.TranscodeProfile
	(*TranscodeProgress)(nil), // 6: v1.TranscodeProgress
	(*Empty)(nil),             // 7: v1.Empty
}
var file_proto_encoder_proto_depIdxs = []int32{
	3, // 0: v1.ProbeResult.streams:type_name -> v1.StreamInfo
	5, // 1: v1.TranscodeRequest.profile:type_name -> v1.TranscodeProfile
	7, // 2: v1.EncoderService.GetCapabilities:input_type -> v1.Empty
	1, // 3: v1.EncoderService.Probe:input_type -> v1.ProbeRequest
	4, // 4: v1.EncoderService.Transcode:input_type -> v1.TranscodeRequest
	0, // 5: v1.EncoderService.GetCapabilities:output_type -> v1.Capabilities
	2, // 6: v1.EncoderService.Probe:output_type -> v1.ProbeResult
	6, // 7: v1.EncoderService.Transcode:output_type -> v1.TranscodeProgress
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_encoder_proto_init() }
func file_proto_encoder_proto_init() {
	if File_proto_encoder_proto != nil {
		return
	}
	file_proto_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_encoder_proto_rawDesc), len(file_proto_encoder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_encoder_proto_goTypes,
		DependencyIndexes: file_proto_encoder_proto_depIdxs,
		MessageInfos:      file_proto_encoder_proto_msgTypes,
	}.Build()
	File_proto_encoder_proto = out.File
	file_proto_encoder_proto_goTypes = nil
	file_proto_encoder_proto_depIdxs = nil
}
