// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/encoder.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EncoderService_GetCapabilities_FullMethodName = "/v1.EncoderService/GetCapabilities"
	EncoderService_Probe_FullMethodName           = "/v1.EncoderService/Probe"
	EncoderService_Transcode_FullMethodName       = "/v1.EncoderService/Transcode"
)

// EncoderServiceClient is the client API for EncoderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncoderServiceClient interface {
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
	Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResult, error)
	Transcode(ctx context.Context, in *TranscodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranscodeProgress], error)
}

type encoderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEncoderServiceClient(cc grpc.ClientConnInterface) EncoderServiceClient {
	return &encoderServiceClient{cc}
}

func (c *encoderServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, EncoderService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encoderServiceClient) Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeResult)
	err := c.cc.Invoke(ctx, EncoderService_Probe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encoderServiceClient) Transcode(ctx context.Context, in *TranscodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranscodeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EncoderService_ServiceDesc.Streams[0], EncoderService_Transcode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscodeRequest, TranscodeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EncoderService_TranscodeClient = grpc.ServerStreamingClient[TranscodeProgress]

// EncoderServiceServer is the server API for EncoderService service.
// All implementations must embed UnimplementedEncoderServiceServer
// for forward compatibility.
type EncoderServiceServer interface {
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	Probe(context.Context, *ProbeRequest) (*ProbeResult, error)
	Transcode(*TranscodeRequest, grpc.ServerStreamingServer[TranscodeProgress]) error
	mustEmbedUnimplementedEncoderServiceServer()
}

// UnimplementedEncoderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncoderServiceServer struct{}

func (UnimplementedEncoderServiceServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedEncoderServiceServer) Probe(context.Context, *ProbeRequest) (*ProbeResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Probe not implemented")
}
func (UnimplementedEncoderServiceServer) Transcode(*TranscodeRequest, grpc.ServerStreamingServer[TranscodeProgress]) error {
	return status.Error(codes.Unimplemented, "method Transcode not implemented")
}
func (UnimplementedEncoderServiceServer) mustEmbedUnimplementedEncoderServiceServer() {}
func (UnimplementedEncoderServiceServer) testEmbeddedByValue()                        {}

// UnsafeEncoderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncoderServiceServer will
// result in compilation errors.
type UnsafeEncoderServiceServer interface {
	mustEmbedUnimplementedEncoderServiceServer()
}

func RegisterEncoderServiceServer(s grpc.ServiceRegistrar, srv EncoderServiceServer) {
	// If the following call panics, it indicates UnimplementedEncoderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EncoderService_ServiceDesc, srv)
}

func _EncoderService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncoderServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncoderService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncoderServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncoderService_Probe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncoderServiceServer).Probe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncoderService_Probe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncoderServiceServer).Probe(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncoderService_Transcode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranscodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EncoderServiceServer).Transcode(m, &grpc.GenericServerStream[TranscodeRequest, TranscodeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EncoderService_TranscodeServer = grpc.ServerStreamingServer[TranscodeProgress]

// EncoderService_ServiceDesc is the grpc.ServiceDesc for EncoderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncoderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.EncoderService",
	HandlerType: (*EncoderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _EncoderService_GetCapabilities_Handler,
		},
		{
			MethodName: "Probe",
			Handler:    _EncoderService_Probe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transcode",
			Handler:       _EncoderService_Transcode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/encoder.proto",
}
