// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/live.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamKey     string                 `protobuf:"bytes,1,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // rtmp, srt, webrtc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestConfig) Reset() {
	*x = IngestConfig{}
	mi := &file_proto_live_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestConfig) ProtoMessage() {}

func (x *IngestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestConfig.ProtoReflect.Descriptor instead.
func (*IngestConfig) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{0}
}

func (x *IngestConfig) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *IngestConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type SessionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionID) Reset() {
	*x = SessionID{}
	mi := &file_proto_live_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionID) ProtoMessage() {}

func (x *SessionID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionID.ProtoReflect.Descriptor instead.
func (*SessionID) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{1}
}

func (x *SessionID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IngestSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IngestUrl     string                 `protobuf:"bytes,2,opt,name=ingest_url,json=ingestUrl,proto3" json:"ingest_url,omitempty"`
	PlaybackUrl   string                 `protobuf:"bytes,3,opt,name=playback_url,json=playbackUrl,proto3" json:"playback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSession) Reset() {
	*x = IngestSession{}
	mi := &file_proto_live_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSession) ProtoMessage() {}

func (x *IngestSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSession.ProtoReflect.Descriptor instead.
func (*IngestSession) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{2}
}

func (x *IngestSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestSession) GetIngestUrl() string {
	if x != nil {
		return x.IngestUrl
	}
	return ""
}

func (x *IngestSession) GetPlaybackUrl() string {
	if x != nil {
		return x.PlaybackUrl
	}
	return ""
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLive        bool                   `protobuf:"varint,1,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	Bitrate       int64                  `protobuf:"varint,2,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Fps           int32                  `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	Viewers       int64                  `protobuf:"varint,4,opt,name=viewers,proto3" json:"viewers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_proto_live_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{3}
}

func (x *Telemetry) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

func (x *Telemetry) GetBitrate() int64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *Telemetry) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *Telemetry) GetViewers() int64 {
	if x != nil {
		return x.Viewers
	}
	return 0
}

type AddOutputTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"` // Full RTMP URL including key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOutputTargetRequest) Reset() {
	*x = AddOutputTargetRequest{}
	mi := &file_proto_live_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOutputTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOutputTargetRequest) ProtoMessage() {}

func (x *AddOutputTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOutputTargetRequest.ProtoReflect.Descriptor instead.
func (*AddOutputTargetRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{4}
}

func (x *AddOutputTargetRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddOutputTargetRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

type RemoveOutputTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOutputTargetRequest) Reset() {
	*x = RemoveOutputTargetRequest{}
	mi := &file_proto_live_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOutputTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOutputTargetRequest) ProtoMessage() {}

func (x *RemoveOutputTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOutputTargetRequest.ProtoReflect.Descriptor instead.
func (*RemoveOutputTargetRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveOutputTargetRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoveOutputTargetRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

var File_proto_live_proto protoreflect.FileDescriptor

const file_proto_live_proto_rawDesc = "" +
	"\n" +
	"\x10proto/live.proto\x12\x02v1\x1a\x12proto/shared.proto\"I\n" +
	"\fIngestConfig\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x01 \x01(\tR\tstreamKey\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\"\x1b\n" +
	"\tSessionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\rIngestSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ingest_url\x18\x02 \x01(\tR\tingestUrl\x12!\n" +
	"\fplayback_url\x18\x03 \x01(\tR\vplaybackUrl\"j\n" +
	"\tTelemetry\x12\x17\n" +
	"\ais_live\x18\x01 \x01(\bR\x06isLive\x12\x18\n" +
	"\abitrate\x18\x02 \x01(\x03R\abitrate\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\x05R\x03fps\x12\x18\n" +
	"\aviewers\x18\x04 \x01(\x03R\aviewers\"V\n" +
	"\x16AddOutputTargetRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\"Y\n" +
	"\x19RemoveOutputTargetRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl2\x91\x02\n" +
	"\vLiveService\x122\n" +
	"\vStartIngest\x12\x10.v1.IngestConfig\x1a\x11.v1.IngestSession\x12&\n" +
	"\n" +
	"StopIngest\x12\r.v1.SessionID\x1a\t.v1.Empty\x12,\n" +
	"\fGetTelemetry\x12\r.v1.SessionID\x1a\r.v1.Telemetry\x128\n" +
	"\x0fAddOutputTarget\x12\x1a.v1.AddOutputTargetRequest\x1a\t.v1.Empty\x12>\n" +
	"\x12RemoveOutputTarget\x12\x1d.v1.RemoveOutputTargetRequest\x1a\t.v1.EmptyB,Z*github.com/rennerdo30/webencode/pkg/api/v1b\x06proto3"

var (
	file_proto_live_proto_rawDescOnce sync.Once
	file_proto_live_proto_rawDescData []byte
)

func file_proto_live_proto_rawDescGZIP() []byte {
	file_proto_live_proto_rawDescOnce.Do(func() {
		file_proto_live_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_live_proto_rawDesc), len(file_proto_live_proto_rawDesc)))
	})
	return file_proto_live_proto_rawDescData
}

var file_proto_live_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_live_proto_goTypes = []any{
	(*IngestConfig)(nil),              // 0: v1.IngestConfig
	(*SessionID)(nil),                 // 1: v1.SessionID
	(*IngestSession)(nil),             // 2: v1.IngestSession
	(*Telemetry)(nil),                 // 3: v1.Telemetry
	(*AddOutputTargetRequest)(nil),    // 4: v1.AddOutputTargetRequest
	(*RemoveOutputTargetRequest)(nil), // 5: v1.RemoveOutputTargetRequest
	(*Empty)(nil),                     // 6: v1.Empty
}
var file_proto_live_proto_depIdxs = []int32{
	0, // 0: v1.LiveService.StartIngest:input_type -> v1.IngestConfig
	1, // 1: v1.LiveService.StopIngest:input_type -> v1.SessionID
	1, // 2: v1.LiveService.GetTelemetry:input_type -> v1.SessionID
	4, // 3: v1.LiveService.AddOutputTarget:input_type -> v1.AddOutputTargetRequest
	5, // 4: v1.LiveService.RemoveOutputTarget:input_type -> v1.RemoveOutputTargetRequest
	2, // 5: v1.LiveService.StartIngest:output_type -> v1.IngestSession
	6, // 6: v1.LiveService.StopIngest:output_type -> v1.Empty
	3, // 7: v1.LiveService.GetTelemetry:output_type -> v1.Telemetry
	6, // 8: v1.LiveService.AddOutputTarget:output_type -> v1.Empty
	6, // 9: v1.LiveService.RemoveOutputTarget:output_type -> v1.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_live_proto_init() }
func file_proto_live_proto_init() {
	if File_proto_live_proto != nil {
		return
	}
	file_proto_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_live_proto_rawDesc), len(file_proto_live_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_live_proto_goTypes,
		DependencyIndexes: file_proto_live_proto_depIdxs,
		MessageInfos:      file_proto_live_proto_msgTypes,
	}.Build()
	File_proto_live_proto = out.File
	file_proto_live_proto_goTypes = nil
	file_proto_live_proto_depIdxs = nil
}
