// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/live.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LiveService_StartIngest_FullMethodName        = "/v1.LiveService/StartIngest"
	LiveService_StopIngest_FullMethodName         = "/v1.LiveService/StopIngest"
	LiveService_GetTelemetry_FullMethodName       = "/v1.LiveService/GetTelemetry"
	LiveService_AddOutputTarget_FullMethodName    = "/v1.LiveService/AddOutputTarget"
	LiveService_RemoveOutputTarget_FullMethodName = "/v1.LiveService/RemoveOutputTarget"
)

// LiveServiceClient is the client API for LiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiveServiceClient interface {
	StartIngest(ctx context.Context, in *IngestConfig, opts ...grpc.CallOption) (*IngestSession, error)
	StopIngest(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Empty, error)
	GetTelemetry(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Telemetry, error)
	// Relay / Restream Support
	AddOutputTarget(ctx context.Context, in *AddOutputTargetRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveOutputTarget(ctx context.Context, in *RemoveOutputTargetRequest, opts ...grpc.CallOption) (*Empty, error)
}

type liveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveServiceClient(cc grpc.ClientConnInterface) LiveServiceClient {
	return &liveServiceClient{cc}
}

func (c *liveServiceClient) StartIngest(ctx context.Context, in *IngestConfig, opts ...grpc.CallOption) (*IngestSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestSession)
	err := c.cc.Invoke(ctx, LiveService_StartIngest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveServiceClient) StopIngest(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LiveService_StopIngest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveServiceClient) GetTelemetry(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Telemetry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Telemetry)
	err := c.cc.Invoke(ctx, LiveService_GetTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveServiceClient) AddOutputTarget(ctx context.Context, in *AddOutputTargetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LiveService_AddOutputTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveServiceClient) RemoveOutputTarget(ctx context.Context, in *RemoveOutputTargetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LiveService_RemoveOutputTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiveServiceServer is the server API for LiveService service.
// All implementations must embed UnimplementedLiveServiceServer
// for forward compatibility.
type LiveServiceServer interface {
	StartIngest(context.Context, *IngestConfig) (*IngestSession, error)
	StopIngest(context.Context, *SessionID) (*Empty, error)
	GetTelemetry(context.Context, *SessionID) (*Telemetry, error)
	// Relay / Restream Support
	AddOutputTarget(context.Context, *AddOutputTargetRequest) (*Empty, error)
	RemoveOutputTarget(context.Context, *RemoveOutputTargetRequest) (*Empty, error)
	mustEmbedUnimplementedLiveServiceServer()
}

// UnimplementedLiveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiveServiceServer struct{}

func (UnimplementedLiveServiceServer) StartIngest(context.Context, *IngestConfig) (*IngestSession, error) {
	return nil, status.Error(codes.Unimplemented, "method StartIngest not implemented")
}
func (UnimplementedLiveServiceServer) StopIngest(context.Context, *SessionID) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopIngest not implemented")
}
func (UnimplementedLiveServiceServer) GetTelemetry(context.Context, *SessionID) (*Telemetry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelemetry not implemented")
}
func (UnimplementedLiveServiceServer) AddOutputTarget(context.Context, *AddOutputTargetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOutputTarget not implemented")
}
func (UnimplementedLiveServiceServer) RemoveOutputTarget(context.Context, *RemoveOutputTargetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOutputTarget not implemented")
}
func (UnimplementedLiveServiceServer) mustEmbedUnimplementedLiveServiceServer() {}
func (UnimplementedLiveServiceServer) testEmbeddedByValue()                     {}

// UnsafeLiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveServiceServer will
// result in compilation errors.
type UnsafeLiveServiceServer interface {
	mustEmbedUnimplementedLiveServiceServer()
}

func RegisterLiveServiceServer(s grpc.ServiceRegistrar, srv LiveServiceServer) {
	// If the following call panics, it indicates UnimplementedLiveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiveService_ServiceDesc, srv)
}

func _LiveService_StartIngest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServiceServer).StartIngest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveService_StartIngest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServiceServer).StartIngest(ctx, req.(*IngestConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveService_StopIngest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServiceServer).StopIngest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveService_StopIngest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServiceServer).StopIngest(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveService_GetTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServiceServer).GetTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveService_GetTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServiceServer).GetTelemetry(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveService_AddOutputTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOutputTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServiceServer).AddOutputTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveService_AddOutputTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServiceServer).AddOutputTarget(ctx, req.(*AddOutputTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveService_RemoveOutputTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOutputTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServiceServer).RemoveOutputTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveService_RemoveOutputTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServiceServer).RemoveOutputTarget(ctx, req.(*RemoveOutputTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiveService_ServiceDesc is the grpc.ServiceDesc for LiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LiveService",
	HandlerType: (*LiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartIngest",
			Handler:    _LiveService_StartIngest_Handler,
		},
		{
			MethodName: "StopIngest",
			Handler:    _LiveService_StopIngest_Handler,
		},
		{
			MethodName: "GetTelemetry",
			Handler:    _LiveService_GetTelemetry_Handler,
		},
		{
			MethodName: "AddOutputTarget",
			Handler:    _LiveService_AddOutputTarget_Handler,
		},
		{
			MethodName: "RemoveOutputTarget",
			Handler:    _LiveService_RemoveOutputTarget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/live.proto",
}
