// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/publisher.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // youtube, twitch
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AccessToken   string                 `protobuf:"bytes,6,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // Or reference to secret
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PublishRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PublishRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *PublishRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type PublishResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    string                 `protobuf:"bytes,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResult) Reset() {
	*x = PublishResult{}
	mi := &file_proto_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResult) ProtoMessage() {}

func (x *PublishResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResult.ProtoReflect.Descriptor instead.
func (*PublishResult) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResult) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *PublishResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RetractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformId    string                 `protobuf:"bytes,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractRequest) Reset() {
	*x = RetractRequest{}
	mi := &file_proto_publisher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractRequest) ProtoMessage() {}

func (x *RetractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractRequest.ProtoReflect.Descriptor instead.
func (*RetractRequest) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{2}
}

func (x *RetractRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RetractRequest) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *RetractRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetLiveStreamEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveStreamEndpointRequest) Reset() {
	*x = GetLiveStreamEndpointRequest{}
	mi := &file_proto_publisher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveStreamEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveStreamEndpointRequest) ProtoMessage() {}

func (x *GetLiveStreamEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveStreamEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetLiveStreamEndpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{3}
}

func (x *GetLiveStreamEndpointRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetLiveStreamEndpointRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GetLiveStreamEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RtmpUrl       string                 `protobuf:"bytes,1,opt,name=rtmp_url,json=rtmpUrl,proto3" json:"rtmp_url,omitempty"`       // e.g., "rtmp://live.twitch.tv/app/"
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"` // e.g., "live_12345_..."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveStreamEndpointResponse) Reset() {
	*x = GetLiveStreamEndpointResponse{}
	mi := &file_proto_publisher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveStreamEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveStreamEndpointResponse) ProtoMessage() {}

func (x *GetLiveStreamEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveStreamEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetLiveStreamEndpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{4}
}

func (x *GetLiveStreamEndpointResponse) GetRtmpUrl() string {
	if x != nil {
		return x.RtmpUrl
	}
	return ""
}

func (x *GetLiveStreamEndpointResponse) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

type GetChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SinceId       string                 `protobuf:"bytes,4,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"` // Checkpoint for polling
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMessagesRequest) Reset() {
	*x = GetChatMessagesRequest{}
	mi := &file_proto_publisher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessagesRequest) ProtoMessage() {}

func (x *GetChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatMessagesRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetChatMessagesRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetChatMessagesRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetChatMessagesRequest) GetSinceId() string {
	if x != nil {
		return x.SinceId
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_publisher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ChatMessage) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetChatMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextSinceId   string                 `protobuf:"bytes,2,opt,name=next_since_id,json=nextSinceId,proto3" json:"next_since_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMessagesResponse) Reset() {
	*x = GetChatMessagesResponse{}
	mi := &file_proto_publisher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessagesResponse) ProtoMessage() {}

func (x *GetChatMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetChatMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatMessagesResponse) GetNextSinceId() string {
	if x != nil {
		return x.NextSinceId
	}
	return ""
}

type SendChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMessageRequest) Reset() {
	*x = SendChatMessageRequest{}
	mi := &file_proto_publisher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageRequest) ProtoMessage() {}

func (x *SendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publisher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*SendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_publisher_proto_rawDescGZIP(), []int{8}
}

func (x *SendChatMessageRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SendChatMessageRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SendChatMessageRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendChatMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_publisher_proto protoreflect.FileDescriptor

const file_proto_publisher_proto_rawDesc = "" +
	"\n" +
	"\x15proto/publisher.proto\x12\x02v1\x1a\x12proto/shared.proto\"\xb9\x01\n" +
	"\x0ePublishRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\faccess_token\x18\x06 \x01(\tR\vaccessToken\"B\n" +
	"\rPublishResult\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\tR\n" +
	"platformId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"p\n" +
	"\x0eRetractRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\tR\n" +
	"platformId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"]\n" +
	"\x1cGetLiveStreamEndpointRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"Y\n" +
	"\x1dGetLiveStreamEndpointResponse\x12\x19\n" +
	"\brtmp_url\x18\x01 \x01(\tR\artmpUrl\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\"\x91\x01\n" +
	"\x16GetChatMessagesRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x19\n" +
	"\bsince_id\x18\x04 \x01(\tR\asinceId\"\x92\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"j\n" +
	"\x17GetChatMessagesResponse\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.v1.ChatMessageR\bmessages\x12\"\n" +
	"\rnext_since_id\x18\x02 \x01(\tR\vnextSinceId\"\x90\x01\n" +
	"\x16SendChatMessageRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xd2\x02\n" +
	"\x10PublisherService\x120\n" +
	"\aPublish\x12\x12.v1.PublishRequest\x1a\x11.v1.PublishResult\x12(\n" +
	"\aRetract\x12\x12.v1.RetractRequest\x1a\t.v1.Empty\x12\\\n" +
	"\x15GetLiveStreamEndpoint\x12 .v1.GetLiveStreamEndpointRequest\x1a!.v1.GetLiveStreamEndpointResponse\x12J\n" +
	"\x0fGetChatMessages\x12\x1a.v1.GetChatMessagesRequest\x1a\x1b.v1.GetChatMessagesResponse\x128\n" +
	"\x0fSendChatMessage\x12\x1a.v1.SendChatMessageRequest\x1a\t.v1.EmptyB,Z*github.com/rennerdo30/webencode/pkg/api/v1b\x06proto3"

var (
	file_proto_publisher_proto_rawDescOnce sync.Once
	file_proto_publisher_proto_rawDescData []byte
)

func file_proto_publisher_proto_rawDescGZIP() []byte {
	file_proto_publisher_proto_rawDescOnce.Do(func() {
		file_proto_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_publisher_proto_rawDesc), len(file_proto_publisher_proto_rawDesc)))
	})
	return file_proto_publisher_proto_rawDescData
}

var file_proto_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_publisher_proto_goTypes = []any{
	(*PublishRequest)(nil),                // 0: v1.PublishRequest
	(*PublishResult)(nil),                 // 1: v1.PublishResult
	(*RetractRequest)(nil),                // 2: v1.RetractRequest
	(*GetLiveStreamEndpointRequest)(nil),  // 3: v1.GetLiveStreamEndpointRequest
	(*GetLiveStreamEndpointResponse)(nil), // 4: v1.GetLiveStreamEndpointResponse
	(*GetChatMessagesRequest)(nil),        // 5: v1.GetChatMessagesRequest
	(*ChatMessage)(nil),                   // 6: v1.ChatMessage
	(*GetChatMessagesResponse)(nil),       // 7: v1.GetChatMessagesResponse
	(*SendChatMessageRequest)(nil),        // 8: v1.SendChatMessageRequest
	(*Empty)(nil),                         // 9: v1.Empty
}
var file_proto_publisher_proto_depIdxs = []int32{
	6, // 0: v1.GetChatMessagesResponse.messages:type_name -> v1.ChatMessage
	0, // 1: v1.PublisherService.Publish:input_type -> v1.PublishRequest
	2, // 2: v1.PublisherService.Retract:input_type -> v1.RetractRequest
	3, // 3: v1.PublisherService.GetLiveStreamEndpoint:input_type -> v1.GetLiveStreamEndpointRequest
	5, // 4: v1.PublisherService.GetChatMessages:input_type -> v1.GetChatMessagesRequest
	8, // 5: v1.PublisherService.SendChatMessage:input_type -> v1.SendChatMessageRequest
	1, // 6: v1.PublisherService.Publish:output_type -> v1.PublishResult
	9, // 7: v1.PublisherService.Retract:output_type -> v1.Empty
	4, // 8: v1.PublisherService.GetLiveStreamEndpoint:output_type -> v1.GetLiveStreamEndpointResponse
	7, // 9: v1.PublisherService.GetChatMessages:output_type -> v1.GetChatMessagesResponse
	9, // 10: v1.PublisherService.SendChatMessage:output_type -> v1.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_publisher_proto_init() }
func file_proto_publisher_proto_init() {
	if File_proto_publisher_proto != nil {
		return
	}
	file_proto_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_publisher_proto_rawDesc), len(file_proto_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_publisher_proto_goTypes,
		DependencyIndexes: file_proto_publisher_proto_depIdxs,
		MessageInfos:      file_proto_publisher_proto_msgTypes,
	}.Build()
	File_proto_publisher_proto = out.File
	file_proto_publisher_proto_goTypes = nil
	file_proto_publisher_proto_depIdxs = nil
}
