// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/storage.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*FileChunk_Metadata
	//	*FileChunk_Data
	Content       isFileChunk_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetContent() isFileChunk_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Content.(*FileChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*FileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isFileChunk_Content interface {
	isFileChunk_Content()
}

type FileChunk_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type FileChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*FileChunk_Metadata) isFileChunk_Content() {}

func (*FileChunk_Data) isFileChunk_Content() {}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSummary) Reset() {
	*x = UploadSummary{}
	mi := &file_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSummary) ProtoMessage() {}

func (x *UploadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSummary.ProtoReflect.Descriptor instead.
func (*UploadSummary) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadSummary) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadSummary) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadSummary) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *FileRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SignedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ExpirySeconds int64                  `protobuf:"varint,3,opt,name=expiry_seconds,json=expirySeconds,proto3" json:"expiry_seconds,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"` // "GET" or "PUT"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedUrlRequest) Reset() {
	*x = SignedUrlRequest{}
	mi := &file_proto_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedUrlRequest) ProtoMessage() {}

func (x *SignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedUrlRequest.ProtoReflect.Descriptor instead.
func (*SignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{4}
}

func (x *SignedUrlRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SignedUrlRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *SignedUrlRequest) GetExpirySeconds() int64 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

func (x *SignedUrlRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SignedUrlRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type SignedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedUrlResponse) Reset() {
	*x = SignedUrlResponse{}
	mi := &file_proto_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedUrlResponse) ProtoMessage() {}

func (x *SignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedUrlResponse.ProtoReflect.Descriptor instead.
func (*SignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{5}
}

func (x *SignedUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SignedUrlResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SignedUrlResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ListObjectsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Bucket            string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix            string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Delimiter         string                 `protobuf:"bytes,3,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	MaxKeys           int32                  `protobuf:"varint,4,opt,name=max_keys,json=maxKeys,proto3" json:"max_keys,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,5,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_proto_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{6}
}

func (x *ListObjectsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListObjectsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListObjectsRequest) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

func (x *ListObjectsRequest) GetMaxKeys() int32 {
	if x != nil {
		return x.MaxKeys
	}
	return 0
}

func (x *ListObjectsRequest) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type ListObjectsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Objects               []*ObjectInfo          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	CommonPrefixes        []string               `protobuf:"bytes,2,rep,name=common_prefixes,json=commonPrefixes,proto3" json:"common_prefixes,omitempty"`
	NextContinuationToken string                 `protobuf:"bytes,3,opt,name=next_continuation_token,json=nextContinuationToken,proto3" json:"next_continuation_token,omitempty"`
	IsTruncated           bool                   `protobuf:"varint,4,opt,name=is_truncated,json=isTruncated,proto3" json:"is_truncated,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_proto_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ListObjectsResponse) GetObjects() []*ObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetCommonPrefixes() []string {
	if x != nil {
		return x.CommonPrefixes
	}
	return nil
}

func (x *ListObjectsResponse) GetNextContinuationToken() string {
	if x != nil {
		return x.NextContinuationToken
	}
	return ""
}

func (x *ListObjectsResponse) GetIsTruncated() bool {
	if x != nil {
		return x.IsTruncated
	}
	return false
}

type ObjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified  int64                  `protobuf:"varint,4,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	StorageClass  string                 `protobuf:"bytes,5,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	mi := &file_proto_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ObjectInfo) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *ObjectInfo) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

type ObjectMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified  int64                  `protobuf:"varint,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	UserMetadata  map[string]string      `protobuf:"bytes,6,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMetadata) Reset() {
	*x = ObjectMetadata{}
	mi := &file_proto_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMetadata) ProtoMessage() {}

func (x *ObjectMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMetadata.ProtoReflect.Descriptor instead.
func (*ObjectMetadata) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{9}
}

func (x *ObjectMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectMetadata) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ObjectMetadata) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *ObjectMetadata) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

// StorageCapabilities describes what features a storage plugin supports
type StorageCapabilities struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SupportsBrowse     bool                   `protobuf:"varint,1,opt,name=supports_browse,json=supportsBrowse,proto3" json:"supports_browse,omitempty"`               // Can browse filesystem/bucket contents
	SupportsUpload     bool                   `protobuf:"varint,2,opt,name=supports_upload,json=supportsUpload,proto3" json:"supports_upload,omitempty"`               // Can upload via API
	SupportsSignedUrls bool                   `protobuf:"varint,3,opt,name=supports_signed_urls,json=supportsSignedUrls,proto3" json:"supports_signed_urls,omitempty"` // Can generate signed URLs
	SupportsStreaming  bool                   `protobuf:"varint,4,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`      // Supports streaming upload/download
	StorageType        string                 `protobuf:"bytes,5,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`                         // "filesystem", "s3", "seaweedfs", etc.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StorageCapabilities) Reset() {
	*x = StorageCapabilities{}
	mi := &file_proto_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageCapabilities) ProtoMessage() {}

func (x *StorageCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageCapabilities.ProtoReflect.Descriptor instead.
func (*StorageCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{10}
}

func (x *StorageCapabilities) GetSupportsBrowse() bool {
	if x != nil {
		return x.SupportsBrowse
	}
	return false
}

func (x *StorageCapabilities) GetSupportsUpload() bool {
	if x != nil {
		return x.SupportsUpload
	}
	return false
}

func (x *StorageCapabilities) GetSupportsSignedUrls() bool {
	if x != nil {
		return x.SupportsSignedUrls
	}
	return false
}

func (x *StorageCapabilities) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *StorageCapabilities) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

// BrowseRootsResponse contains available root directories
type BrowseRootsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*BrowseEntry         `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseRootsResponse) Reset() {
	*x = BrowseRootsResponse{}
	mi := &file_proto_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseRootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseRootsResponse) ProtoMessage() {}

func (x *BrowseRootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseRootsResponse.ProtoReflect.Descriptor instead.
func (*BrowseRootsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{11}
}

func (x *BrowseRootsResponse) GetRoots() []*BrowseEntry {
	if x != nil {
		return x.Roots
	}
	return nil
}

// BrowseRequest is used to browse a directory
type BrowseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                  // Directory path to browse
	ShowHidden    bool                   `protobuf:"varint,2,opt,name=show_hidden,json=showHidden,proto3" json:"show_hidden,omitempty"`   // Include hidden files (starting with .)
	MediaOnly     bool                   `protobuf:"varint,3,opt,name=media_only,json=mediaOnly,proto3" json:"media_only,omitempty"`      // Only show video/audio/image files
	SearchQuery   string                 `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // Optional: filter by name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseRequest) Reset() {
	*x = BrowseRequest{}
	mi := &file_proto_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseRequest) ProtoMessage() {}

func (x *BrowseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseRequest.ProtoReflect.Descriptor instead.
func (*BrowseRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{12}
}

func (x *BrowseRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BrowseRequest) GetShowHidden() bool {
	if x != nil {
		return x.ShowHidden
	}
	return false
}

func (x *BrowseRequest) GetMediaOnly() bool {
	if x != nil {
		return x.MediaOnly
	}
	return false
}

func (x *BrowseRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

// BrowseResponse contains directory listing
type BrowseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPath   string                 `protobuf:"bytes,1,opt,name=current_path,json=currentPath,proto3" json:"current_path,omitempty"`
	ParentPath    string                 `protobuf:"bytes,2,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"` // Empty if at root or no access to parent
	Entries       []*BrowseEntry         `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseResponse) Reset() {
	*x = BrowseResponse{}
	mi := &file_proto_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseResponse) ProtoMessage() {}

func (x *BrowseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseResponse.ProtoReflect.Descriptor instead.
func (*BrowseResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{13}
}

func (x *BrowseResponse) GetCurrentPath() string {
	if x != nil {
		return x.CurrentPath
	}
	return ""
}

func (x *BrowseResponse) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *BrowseResponse) GetEntries() []*BrowseEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// BrowseEntry represents a file or directory
type BrowseEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // Full path
	IsDirectory   bool                   `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                      // 0 for directories
	ModTime       int64                  `protobuf:"varint,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"` // Unix timestamp
	Extension     string                 `protobuf:"bytes,6,opt,name=extension,proto3" json:"extension,omitempty"`             // File extension without dot
	IsVideo       bool                   `protobuf:"varint,7,opt,name=is_video,json=isVideo,proto3" json:"is_video,omitempty"`
	IsAudio       bool                   `protobuf:"varint,8,opt,name=is_audio,json=isAudio,proto3" json:"is_audio,omitempty"`
	IsImage       bool                   `protobuf:"varint,9,opt,name=is_image,json=isImage,proto3" json:"is_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseEntry) Reset() {
	*x = BrowseEntry{}
	mi := &file_proto_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseEntry) ProtoMessage() {}

func (x *BrowseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseEntry.ProtoReflect.Descriptor instead.
func (*BrowseEntry) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{14}
}

func (x *BrowseEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrowseEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BrowseEntry) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *BrowseEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BrowseEntry) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *BrowseEntry) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *BrowseEntry) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

func (x *BrowseEntry) GetIsAudio() bool {
	if x != nil {
		return x.IsAudio
	}
	return false
}

func (x *BrowseEntry) GetIsImage() bool {
	if x != nil {
		return x.IsImage
	}
	return false
}

var File_proto_storage_proto protoreflect.FileDescriptor

const file_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x13proto/storage.proto\x12\x02v1\x1a\x12proto/shared.proto\"\\\n" +
	"\tFileChunk\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.v1.FileMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\acontent\"q\n" +
	"\fFileMetadata\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"I\n" +
	"\rUploadSummary\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\"9\n" +
	"\vFileRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xab\x01\n" +
	"\x10SignedUrlRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12%\n" +
	"\x0eexpiry_seconds\x18\x03 \x01(\x03R\rexpirySeconds\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\"\xbe\x01\n" +
	"\x11SignedUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12<\n" +
	"\aheaders\x18\x02 \x03(\v2\".v1.SignedUrlResponse.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x12ListObjectsRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x1c\n" +
	"\tdelimiter\x18\x03 \x01(\tR\tdelimiter\x12\x19\n" +
	"\bmax_keys\x18\x04 \x01(\x05R\amaxKeys\x12-\n" +
	"\x12continuation_token\x18\x05 \x01(\tR\x11continuationToken\"\xc3\x01\n" +
	"\x13ListObjectsResponse\x12(\n" +
	"\aobjects\x18\x01 \x03(\v2\x0e.v1.ObjectInfoR\aobjects\x12'\n" +
	"\x0fcommon_prefixes\x18\x02 \x03(\tR\x0ecommonPrefixes\x126\n" +
	"\x17next_continuation_token\x18\x03 \x01(\tR\x15nextContinuationToken\x12!\n" +
	"\fis_truncated\x18\x04 \x01(\bR\visTruncated\"\x90\x01\n" +
	"\n" +
	"ObjectInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x12#\n" +
	"\rlast_modified\x18\x04 \x01(\x03R\flastModified\x12#\n" +
	"\rstorage_class\x18\x05 \x01(\tR\fstorageClass\"\x9e\x02\n" +
	"\x0eObjectMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12#\n" +
	"\rlast_modified\x18\x05 \x01(\x03R\flastModified\x12I\n" +
	"\ruser_metadata\x18\x06 \x03(\v2$.v1.ObjectMetadata.UserMetadataEntryR\fuserMetadata\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x13StorageCapabilities\x12'\n" +
	"\x0fsupports_browse\x18\x01 \x01(\bR\x0esupportsBrowse\x12'\n" +
	"\x0fsupports_upload\x18\x02 \x01(\bR\x0esupportsUpload\x120\n" +
	"\x14supports_signed_urls\x18\x03 \x01(\bR\x12supportsSignedUrls\x12-\n" +
	"\x12supports_streaming\x18\x04 \x01(\bR\x11supportsStreaming\x12!\n" +
	"\fstorage_type\x18\x05 \x01(\tR\vstorageType\"<\n" +
	"\x13BrowseRootsResponse\x12%\n" +
	"\x05roots\x18\x01 \x03(\v2\x0f.v1.BrowseEntryR\x05roots\"\x86\x01\n" +
	"\rBrowseRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vshow_hidden\x18\x02 \x01(\bR\n" +
	"showHidden\x12\x1d\n" +
	"\n" +
	"media_only\x18\x03 \x01(\bR\tmediaOnly\x12!\n" +
	"\fsearch_query\x18\x04 \x01(\tR\vsearchQuery\"\x7f\n" +
	"\x0eBrowseResponse\x12!\n" +
	"\fcurrent_path\x18\x01 \x01(\tR\vcurrentPath\x12\x1f\n" +
	"\vparent_path\x18\x02 \x01(\tR\n" +
	"parentPath\x12)\n" +
	"\aentries\x18\x03 \x03(\v2\x0f.v1.BrowseEntryR\aentries\"\xf6\x01\n" +
	"\vBrowseEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fis_directory\x18\x03 \x01(\bR\visDirectory\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\x03R\amodTime\x12\x1c\n" +
	"\textension\x18\x06 \x01(\tR\textension\x12\x19\n" +
	"\bis_video\x18\a \x01(\bR\aisVideo\x12\x19\n" +
	"\bis_audio\x18\b \x01(\bR\aisAudio\x12\x19\n" +
	"\bis_image\x18\t \x01(\bR\aisImage2\x9b\x04\n" +
	"\x0eStorageService\x12,\n" +
	"\x06Upload\x12\r.v1.FileChunk\x1a\x11.v1.UploadSummary(\x01\x12,\n" +
	"\bDownload\x12\x0f.v1.FileRequest\x1a\r.v1.FileChunk0\x01\x12$\n" +
	"\x06Delete\x12\x0f.v1.FileRequest\x1a\t.v1.Empty\x125\n" +
	"\x06GetURL\x12\x14.v1.SignedUrlRequest\x1a\x15.v1.SignedUrlResponse\x12;\n" +
	"\fGetUploadURL\x12\x14.v1.SignedUrlRequest\x1a\x15.v1.SignedUrlResponse\x12>\n" +
	"\vListObjects\x12\x16.v1.ListObjectsRequest\x1a\x17.v1.ListObjectsResponse\x128\n" +
	"\x11GetObjectMetadata\x12\x0f.v1.FileRequest\x1a\x12.v1.ObjectMetadata\x125\n" +
	"\x0fGetCapabilities\x12\t.v1.Empty\x1a\x17.v1.StorageCapabilities\x121\n" +
	"\vBrowseRoots\x12\t.v1.Empty\x1a\x17.v1.BrowseRootsResponse\x12/\n" +
	"\x06Browse\x12\x11.v1.BrowseRequest\x1a\x12.v1.BrowseResponseB,Z*github.com/rennerdo30/webencode/pkg/api/v1b\x06proto3"

var (
	file_proto_storage_proto_rawDescOnce sync.Once
	file_proto_storage_proto_rawDescData []byte
)

func file_proto_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)))
	})
	return file_proto_storage_proto_rawDescData
}

var file_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_storage_proto_goTypes = []any{
	(*FileChunk)(nil),           // 0: v1.FileChunk
	(*FileMetadata)(nil),        // 1: v1.FileMetadata
	(*UploadSummary)(nil),       // 2: v1.UploadSummary
	(*FileRequest)(nil),         // 3: v1.FileRequest
	(*SignedUrlRequest)(nil),    // 4: v1.SignedUrlRequest
	(*SignedUrlResponse)(nil),   // 5: v1.SignedUrlResponse
	(*ListObjectsRequest)(nil),  // 6: v1.ListObjectsRequest
	(*ListObjectsResponse)(nil), // 7: v1.ListObjectsResponse
	(*ObjectInfo)(nil),          // 8: v1.ObjectInfo
	(*ObjectMetadata)(nil),      // 9: v1.ObjectMetadata
	(*StorageCapabilities)(nil), // 10: v1.StorageCapabilities
	(*BrowseRootsResponse)(nil), // 11: v1.BrowseRootsResponse
	(*BrowseRequest)(nil),       // 12: v1.BrowseRequest
	(*BrowseResponse)(nil),      // 13: v1.BrowseResponse
	(*BrowseEntry)(nil),         // 14: v1.BrowseEntry
	nil,                         // 15: v1.SignedUrlResponse.HeadersEntry
	nil,                         // 16: v1.ObjectMetadata.UserMetadataEntry
	(*Empty)(nil),               // 17: v1.Empty
}
var file_proto_storage_proto_depIdxs = []int32{
	1,  // 0: v1.FileChunk.metadata:type_name -> v1.FileMetadata
	15, // 1: v1.SignedUrlResponse.headers:type_name -> v1.SignedUrlResponse.HeadersEntry
	8,  // 2: v1.ListObjectsResponse.objects:type_name -> v1.ObjectInfo
	16, // 3: v1.ObjectMetadata.user_metadata:type_name -> v1.ObjectMetadata.UserMetadataEntry
	14, // 4: v1.BrowseRootsResponse.roots:type_name -> v1.BrowseEntry
	14, // 5: v1.BrowseResponse.entries:type_name -> v1.BrowseEntry
	0,  // 6: v1.StorageService.Upload:input_type -> v1.FileChunk
	3,  // 7: v1.StorageService.Download:input_type -> v1.FileRequest
	3,  // 8: v1.StorageService.Delete:input_type -> v1.FileRequest
	4,  // 9: v1.StorageService.GetURL:input_type -> v1.SignedUrlRequest
	4,  // 10: v1.StorageService.GetUploadURL:input_type -> v1.SignedUrlRequest
	6,  // 11: v1.StorageService.ListObjects:input_type -> v1.ListObjectsRequest
	3,  // 12: v1.StorageService.GetObjectMetadata:input_type -> v1.FileRequest
	17, // 13: v1.StorageService.GetCapabilities:input_type -> v1.Empty
	17, // 14: v1.StorageService.BrowseRoots:input_type -> v1.Empty
	12, // 15: v1.StorageService.Browse:input_type -> v1.BrowseRequest
	2,  // 16: v1.StorageService.Upload:output_type -> v1.UploadSummary
	0,  // 17: v1.StorageService.Download:output_type -> v1.FileChunk
	17, // 18: v1.StorageService.Delete:output_type -> v1.Empty
	5,  // 19: v1.StorageService.GetURL:output_type -> v1.SignedUrlResponse
	5,  // 20: v1.StorageService.GetUploadURL:output_type -> v1.SignedUrlResponse
	7,  // 21: v1.StorageService.ListObjects:output_type -> v1.ListObjectsResponse
	9,  // 22: v1.StorageService.GetObjectMetadata:output_type -> v1.ObjectMetadata
	10, // 23: v1.StorageService.GetCapabilities:output_type -> v1.StorageCapabilities
	11, // 24: v1.StorageService.BrowseRoots:output_type -> v1.BrowseRootsResponse
	13, // 25: v1.StorageService.Browse:output_type -> v1.BrowseResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_storage_proto_init() }
func file_proto_storage_proto_init() {
	if File_proto_storage_proto != nil {
		return
	}
	file_proto_shared_proto_init()
	file_proto_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*FileChunk_Metadata)(nil),
		(*FileChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_proto = out.File
	file_proto_storage_proto_goTypes = nil
	file_proto_storage_proto_depIdxs = nil
}
