// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/storage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_Upload_FullMethodName            = "/v1.StorageService/Upload"
	StorageService_Download_FullMethodName          = "/v1.StorageService/Download"
	StorageService_Delete_FullMethodName            = "/v1.StorageService/Delete"
	StorageService_GetURL_FullMethodName            = "/v1.StorageService/GetURL"
	StorageService_GetUploadURL_FullMethodName      = "/v1.StorageService/GetUploadURL"
	StorageService_ListObjects_FullMethodName       = "/v1.StorageService/ListObjects"
	StorageService_GetObjectMetadata_FullMethodName = "/v1.StorageService/GetObjectMetadata"
	StorageService_GetCapabilities_FullMethodName   = "/v1.StorageService/GetCapabilities"
	StorageService_BrowseRoots_FullMethodName       = "/v1.StorageService/BrowseRoots"
	StorageService_Browse_FullMethodName            = "/v1.StorageService/Browse"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService provides object storage operations
type StorageServiceClient interface {
	// Upload streams file content to storage
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadSummary], error)
	// Download streams file content from storage
	Download(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// Delete removes an object from storage
	Delete(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetURL returns a signed URL for direct access
	GetURL(ctx context.Context, in *SignedUrlRequest, opts ...grpc.CallOption) (*SignedUrlResponse, error)
	// GetUploadURL returns a pre-signed URL for uploads
	GetUploadURL(ctx context.Context, in *SignedUrlRequest, opts ...grpc.CallOption) (*SignedUrlResponse, error)
	// ListObjects lists objects in a bucket with optional prefix
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	// GetObjectMetadata returns metadata for an object
	GetObjectMetadata(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ObjectMetadata, error)
	// GetCapabilities returns what features this storage plugin supports
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StorageCapabilities, error)
	// BrowseRoots returns available root directories for browsing (if supported)
	BrowseRoots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BrowseRootsResponse, error)
	// Browse lists contents of a directory (if supported)
	Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*BrowseResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_UploadClient = grpc.ClientStreamingClient[FileChunk, UploadSummary]

func (c *storageServiceClient) Download(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_DownloadClient = grpc.ServerStreamingClient[FileChunk]

func (c *storageServiceClient) Delete(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetURL(ctx context.Context, in *SignedUrlRequest, opts ...grpc.CallOption) (*SignedUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedUrlResponse)
	err := c.cc.Invoke(ctx, StorageService_GetURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetUploadURL(ctx context.Context, in *SignedUrlRequest, opts ...grpc.CallOption) (*SignedUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedUrlResponse)
	err := c.cc.Invoke(ctx, StorageService_GetUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, StorageService_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetObjectMetadata(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ObjectMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectMetadata)
	err := c.cc.Invoke(ctx, StorageService_GetObjectMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StorageCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageCapabilities)
	err := c.cc.Invoke(ctx, StorageService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) BrowseRoots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BrowseRootsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseRootsResponse)
	err := c.cc.Invoke(ctx, StorageService_BrowseRoots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*BrowseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseResponse)
	err := c.cc.Invoke(ctx, StorageService_Browse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService provides object storage operations
type StorageServiceServer interface {
	// Upload streams file content to storage
	Upload(grpc.ClientStreamingServer[FileChunk, UploadSummary]) error
	// Download streams file content from storage
	Download(*FileRequest, grpc.ServerStreamingServer[FileChunk]) error
	// Delete removes an object from storage
	Delete(context.Context, *FileRequest) (*Empty, error)
	// GetURL returns a signed URL for direct access
	GetURL(context.Context, *SignedUrlRequest) (*SignedUrlResponse, error)
	// GetUploadURL returns a pre-signed URL for uploads
	GetUploadURL(context.Context, *SignedUrlRequest) (*SignedUrlResponse, error)
	// ListObjects lists objects in a bucket with optional prefix
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	// GetObjectMetadata returns metadata for an object
	GetObjectMetadata(context.Context, *FileRequest) (*ObjectMetadata, error)
	// GetCapabilities returns what features this storage plugin supports
	GetCapabilities(context.Context, *Empty) (*StorageCapabilities, error)
	// BrowseRoots returns available root directories for browsing (if supported)
	BrowseRoots(context.Context, *Empty) (*BrowseRootsResponse, error)
	// Browse lists contents of a directory (if supported)
	Browse(context.Context, *BrowseRequest) (*BrowseResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) Upload(grpc.ClientStreamingServer[FileChunk, UploadSummary]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedStorageServiceServer) Download(*FileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedStorageServiceServer) Delete(context.Context, *FileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStorageServiceServer) GetURL(context.Context, *SignedUrlRequest) (*SignedUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetURL not implemented")
}
func (UnimplementedStorageServiceServer) GetUploadURL(context.Context, *SignedUrlRequest) (*SignedUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadURL not implemented")
}
func (UnimplementedStorageServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedStorageServiceServer) GetObjectMetadata(context.Context, *FileRequest) (*ObjectMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectMetadata not implemented")
}
func (UnimplementedStorageServiceServer) GetCapabilities(context.Context, *Empty) (*StorageCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedStorageServiceServer) BrowseRoots(context.Context, *Empty) (*BrowseRootsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BrowseRoots not implemented")
}
func (UnimplementedStorageServiceServer) Browse(context.Context, *BrowseRequest) (*BrowseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Browse not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).Upload(&grpc.GenericServerStream[FileChunk, UploadSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_UploadServer = grpc.ClientStreamingServer[FileChunk, UploadSummary]

func _StorageService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).Download(m, &grpc.GenericServerStream[FileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_DownloadServer = grpc.ServerStreamingServer[FileChunk]

func _StorageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Delete(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetURL(ctx, req.(*SignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetUploadURL(ctx, req.(*SignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetObjectMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetObjectMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetObjectMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetObjectMetadata(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_BrowseRoots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).BrowseRoots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_BrowseRoots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).BrowseRoots(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Browse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Browse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Browse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Browse(ctx, req.(*BrowseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _StorageService_Delete_Handler,
		},
		{
			MethodName: "GetURL",
			Handler:    _StorageService_GetURL_Handler,
		},
		{
			MethodName: "GetUploadURL",
			Handler:    _StorageService_GetUploadURL_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _StorageService_ListObjects_Handler,
		},
		{
			MethodName: "GetObjectMetadata",
			Handler:    _StorageService_GetObjectMetadata_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _StorageService_GetCapabilities_Handler,
		},
		{
			MethodName: "BrowseRoots",
			Handler:    _StorageService_BrowseRoots_Handler,
		},
		{
			MethodName: "Browse",
			Handler:    _StorageService_Browse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _StorageService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _StorageService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/storage.proto",
}
